Feature 2
banzaman/portfolio-mskeleton pull request #2
Opened 2021-10-29 20:23 UTC by banzaman

Edited HTML,CSS and image file.
Edited HTML and CSS files.
Fixed errors of style.css.

2021-10-29 21:36 UTC, mikethreels requested changes
Hi Creed, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-29 21:36 UTC, mikethreels commented on index.html
> +            </a>
- [ ] Great job on the project so far it looks very similar to the Figma design 👍 the button however is stuck to the top of the next project instead of to the bottom of the project it belongs to, see below print screen examples.
your project:
![127 0 0 1_5500_portfolio-mskeleton_index html (2)](https://user-images.githubusercontent.com/39240820/139503299-c70e5b93-d006-43f5-b427-0cad118c68ee.png)

figma design:
![figma example](https://user-images.githubusercontent.com/39240820/139503355-93b02708-81f6-498c-95a4-9daef47a91c0.PNG)

2021-10-29 21:36 UTC, mikethreels commented on index.html
> +                  />
- [ ] great work aligning the content on your webpage 💪 however as you can see in the print screen of my previous inline comment the list of project technologies are aligned vertically although in the Figma design they are aligned horizontally, I strongly advise you to change this because not all languages are visible due to this.

2021-10-29 21:36 UTC, mikethreels commented on index.html
> +        </ul>
- [ ] good job on the skills section it looks great 🥇 however according to the requirements the technologies categories should be wrapped in a list as well, I'll make a small example below.

```
<ul>
  <li>
    <h2 class="lan">Language</h2>
    <ul class="eniimi">
      <li>Javascript</li>
      <li>Ruby</li>
      <li>HTML</li>
      <li>CSS</li>
    </ul>
  </li>
  <li>
    <h2 class="frame">Frameworks</h2>
    <ul class="eniimi">
      <li>Bootstrap</li>
      <li>Ruby on Rails</li>
      <li>RSPec</li>
      <li>CapyBara</li>
      <li>Selenium</li>
    </ul>
  </li>
  <li>
    <h2 class="ski">Skills</h2>
    <ul class="eniimi">
      <li>Codekit</li>
      <li>Github</li>
      <li>Codepen</li>
      <li>Gitlab</li>
      <li>Terminal</li>
    </ul>
  </li>
</ul>
```

2021-10-30 00:34 UTC, eri8-9 approved these changes
Hi @banzaman , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- I see that you did most of the work, well done!

![Felix](https://media.giphy.com/media/hlQeY3PbhH3i/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-30 07:12 UTC, merged